name: 🚀 Feature Request
description: Suggest a fire new feature for GitTalker
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees:
  - Immutablemike

body:
  - type: markdown
    attributes:
      value: |
        Got an idea to make GitTalker even more fire? We're all ears! 💡
        
        Help us understand what you'd like to see and why it would be valuable.

  - type: textarea
    id: feature-description
    attributes:
      label: What feature would you like to see?
      description: Describe the feature you'd like to add
      placeholder: "I want GitTalker to be able to generate memes based on repository content..."
    validations:
      required: true

  - type: textarea
    id: problem-solution
    attributes:
      label: What problem does this solve?
      description: What pain point or use case would this address?
      placeholder: "Currently, when people ask boring questions, GitTalker gives boring answers. Memes would make everything more engaging..."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Describe your proposed solution
      description: How do you think this feature should work?
      placeholder: "GitTalker could detect when someone asks about complex code and respond with a relevant meme plus the explanation..."

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative approaches
      description: Have you considered any alternative solutions?
      placeholder: "We could also add GIF responses, or just enhance the urban personality instead..."

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature to you?
      options:
        - "🔥 Critical - I need this to use GitTalker effectively"
        - "💯 High - This would significantly improve my experience"
        - "✨ Medium - Nice to have, would be cool"
        - "🤔 Low - Just an idea, no pressure"
    validations:
      required: true

  - type: checkboxes
    id: feature-type
    attributes:
      label: What type of feature is this?
      description: Select all that apply
      options:
        - label: "🎭 Personality/Communication enhancement"
        - label: "🔗 Integration with external service"
        - label: "📊 Data/Analytics feature"
        - label: "🎨 UI/UX improvement"
        - label: "⚡ Performance optimization"
        - label: "🛡️ Security enhancement"
        - label: "📚 Documentation/Help feature"
        - label: "🔧 Developer experience improvement"

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or examples
      placeholder: "Links to similar features, mockups, or anything else that helps explain your idea..."

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true